9 register
HarsaEdu/harsa-api pull request #36
Opened 2023-11-09 07:31 UTC by madya-dev

2023-11-09 11:41 UTC, Aszaychik requested changes
Ada typo di nama file service/contact yg harusnya service/contract

Nama file contract ubah aja ke Interface biar lebih enak/mudah di pahami langsung pas baca file

2023-11-09 11:44 UTC, madya-dev commented
> Ada typo di nama file service/contact yg harusnya service/contract
> 
> Nama file contract ubah aja ke Interface biar lebih enak/mudah di pahami langsung pas baca file

contract.go -> interface.go ya?

2023-11-10 09:31 UTC, Aszaychik commented
Oh ya usahain semua response pake huruf kecil semua,
dan juga install extension error lint sama sonar lint

2023-11-11 16:13 UTC, madya-dev commented
@Aszaychik @yusufUcps bisa di cek ulang mas udah solve

<img width="499" alt="image" src="https://github.com/HarsaEdu/harsa-api/assets/84718700/0d766430-7bda-4c24-870e-6cd364c6dfda">
<img width="940" alt="image" src="https://github.com/HarsaEdu/harsa-api/assets/84718700/ccf1dfa9-6a2e-4688-a5f0-1bbcf53ee910">

2023-11-12 01:01 UTC, Aszaychik approved these changes
NICE

2023-11-12 01:02 UTC, merged